apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/nodeSelector
      value:
        eks.amazonaws.com/nodegroup: gitops
  target:
    kind: Deployment
