apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: employee-app
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: thanushdev01/emp-frontend:46e869d13ba483fb5d08d051eefae32013eca4c7
        ports:
        - containerPort: 80
