apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: employee-app
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: thanushdev01/emp-frontend:7319c3bac007858d90ae65d0fc49db42d26269b2
        ports:
        - containerPort: 80
