apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: employee-app
spec:
  type: LoadBalancer        # ← exposes to internet
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80