apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: employee-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: thanushdev01/emp-backend:v1
        ports:
        - containerPort: 8090
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/employee_db
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: employee-app
spec:
  selector:
    app: backend
  ports:
  - port: 8090
    targetPort: 8090