apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: employee-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: YOUR_DOCKERHUB/emp-frontend:v1   # ← change this to trigger CD
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: employee-app
spec:
  type: LoadBalancer    # exposes on EKS public IP
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80