apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: employee-app
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: thanushdev01/emp-frontend:ca07b1dfd784ae957dacf57c0a3c67a94f18cebf
        ports:
        - containerPort: 80
