apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: employee-app
type: Opaque
stringData:
  MYSQL_DATABASE: employee_db
  MYSQL_USER: employee_user
  MYSQL_PASSWORD: employee123
  MYSQL_ROOT_PASSWORD: rootpass123